"use client";

import { useCallback, useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, Plus, Wand2, X } from "lucide-react";
import { confirmMealPlan, getMealPlan, savePlannedMeal } from "@/lib/api";

const mealTypes = ["Breakfast", "Lunch", "Dinner", "Snack"];
function monday(date = new Date()) { const copy = new Date(date); const day = copy.getDay() || 7; copy.setDate(copy.getDate() - day + 1); copy.setHours(0, 0, 0, 0); return copy; }
function iso(date: Date) { return date.toISOString().slice(0, 10); }

export default function MealPlannerPage() {
  const [start, setStart] = useState(monday()); const [plan, setPlan] = useState<any>(null); const [inventory, setInventory] = useState<any[]>([]); const [suggestions, setSuggestions] = useState<any[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [form, setForm] = useState<any>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const data = await getMealPlan(iso(start)); setPlan(data.plan); setInventory(data.inventory); setSuggestions(data.suggestions); setError(""); } catch (e: any) { setError(e.message); } }, [start]);
  useEffect(() => { load(); }, [load]);
  const dates = Array.from({ length: 7 }, (_, index) => { const value = new Date(start); value.setDate(start.getDate() + index); return value; });
  const open = (date: Date, mealType: string, suggestion?: any) => setForm({ date: iso(date), mealType, name: suggestion?.name || "", cookingTime: suggestion?.cookingTime || "", ingredients: suggestion?.ingredients || [] });
  const save = async () => { if (!form?.name?.trim()) return setError("Enter a meal name."); setSaving(true); try { await savePlannedMeal({ ...form, weekStart: iso(start) }); setForm(null); await load(); } catch (e: any) { setError(e.message); } finally { setSaving(false); } };
  const confirm = async () => { try { const data = await confirmMealPlan(iso(start)); setMessage(data.message); await load(); } catch (e: any) { setError(e.message); } };
  const meals = plan?.meals || []; const confirmed = plan?.status === "CONFIRMED";
  return <div className="space-y-6"><div className="flex flex-col sm:flex-row justify-between gap-3 bg-white p-4 rounded-xl border shadow-sm"><div className="flex items-center gap-3"><button onClick={() => setStart((d) => { const n = new Date(d); n.setDate(n.getDate() - 7); return n; })} className="p-2 border rounded"><ChevronLeft className="w-4 h-4"/></button><b className="w-44 text-center">{start.toLocaleDateString(undefined, { month: "short", day: "numeric" })} – {dates[6].toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}</b><button onClick={() => setStart((d) => { const n = new Date(d); n.setDate(n.getDate() + 7); return n; })} className="p-2 border rounded"><ChevronRight className="w-4 h-4"/></button></div><button disabled={!plan || confirmed} onClick={confirm} className="bg-[#4CAF50] text-white px-4 rounded-md text-sm disabled:opacity-50">{confirmed ? "Plan confirmed" : "Confirm plan & reserve inventory"}</button></div>
  {error && <div className="p-3 bg-red-50 text-red-700 rounded text-sm">{error}</div>}{message && <div className="p-3 bg-green-50 text-green-700 rounded text-sm">{message}</div>}
  <div className="bg-white rounded-xl border overflow-x-auto"><table className="w-full min-w-[850px]"><thead><tr className="bg-gray-50"><th className="p-3 text-left text-xs">Meal</th>{dates.map((date) => <th key={iso(date)} className="p-3 text-sm">{date.toLocaleDateString(undefined, { weekday: "short" })}<small className="block text-gray-400">{date.getDate()}</small></th>)}</tr></thead><tbody>{mealTypes.map((type) => <tr key={type} className="border-t"><th className="p-3 text-xs text-left text-gray-500">{type}</th>{dates.map((date) => { const meal = meals.find((item: any) => item.mealType === type && iso(new Date(item.date)) === iso(date)); return <td key={iso(date)} className="p-2 h-28 align-top">{meal ? <div className="border rounded-lg p-2 text-xs"><b>{meal.name}</b><p className="text-gray-500 mt-1">{meal.ingredients.map((i: any) => i.foodItem.name).join(", ") || "No inventory selected"}</p></div> : <button disabled={confirmed} onClick={() => open(date, type)} className="w-full h-full border-2 border-dashed rounded text-xs text-gray-400 hover:border-gray-300 disabled:hidden"><Plus className="w-3 h-3 inline"/> Add</button>}</td>; })}</tr>)}</tbody></table></div>
  <section><div className="flex gap-2 items-center mb-3"><Wand2 className="w-4 h-4 text-[#4CAF50]"/><h2 className="font-semibold text-sm">Suggestions from inventory</h2></div><div className="grid md:grid-cols-3 gap-3">{suggestions.map((s: any) => <div key={s.ingredients[0]?.foodItemId} className="bg-white border rounded-lg p-4"><b className="text-sm">{s.name}</b><p className="text-xs text-gray-500 mt-1">Uses {s.ingredients.map((i: any) => i.name).join(", ")}</p><button disabled={confirmed} onClick={() => open(dates[0], "Dinner", s)} className="mt-3 text-xs border border-[#4CAF50] text-[#4CAF50] px-3 py-1.5 rounded">Add to Monday dinner</button></div>)}</div></section>
  {form && <div className="fixed inset-0 z-50 bg-black/30 grid place-items-center p-4"><div className="bg-white w-full max-w-md rounded-xl p-5 space-y-3"><div className="flex justify-between"><h2 className="font-semibold">Add {form.mealType}</h2><button onClick={() => setForm(null)}><X/></button></div><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Meal name" className="w-full border rounded h-9 px-3 text-sm"/><select multiple value={form.ingredients.map((i: any) => i.foodItemId)} onChange={(e) => setForm({ ...form, ingredients: Array.from(e.target.selectedOptions).map((o) => { const item = inventory.find((i) => i.id === o.value); return { foodItemId: item.id, name: item.name, quantity: "1", unit: item.unit }; }) })} className="w-full border rounded p-2 text-sm h-32">{inventory.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.quantity} {item.unit})</option>)}</select><p className="text-xs text-gray-500">Use Ctrl/Cmd to choose multiple inventory items. Quantities are reserved only after confirmation.</p><button disabled={saving} onClick={save} className="w-full h-9 bg-[#4CAF50] text-white rounded text-sm">{saving ? "Saving…" : "Save meal"}</button></div></div>}
  </div>;
}
