"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, X, Clock, MapPin } from "lucide-react";
import { getMyDonations, updateDonation } from "@/lib/api";
export default function MyDonationsPage() {
 const [donations, setDonations] = useState<any[]>([]), [error, setError] = useState(""); const load = useCallback(async () => { try { setDonations((await getMyDonations()).donations || []); } catch (e:any) { setError(e.message); } }, []); useEffect(() => { load(); }, [load]);
 const act = async (id:string, action:string) => { try { await updateDonation(id, action); load(); } catch(e:any){setError(e.message);} };
 return <div className="space-y-5"><div><h2 className="font-semibold text-lg">My Donations</h2><p className="text-sm text-gray-500">Approve requests, arrange approved pickups, and complete collected donations.</p></div>{error && <p className="p-3 bg-red-50 text-red-700 rounded text-sm">{error}</p>}<div className="grid gap-4">{donations.map(d => { const donor = d.donorId === JSON.parse(localStorage.getItem("saveplate_user") || "{}").id; return <article key={d.id} className="bg-white border rounded-xl p-5 flex flex-col md:flex-row gap-4 justify-between"><div><div className="flex gap-2 items-center"><b>{d.foodItem.name}</b><span className="text-xs rounded bg-gray-100 px-2 py-1">{d.status}</span></div><p className="text-sm text-gray-500 mt-1">{d.foodItem.quantity} {d.foodItem.unit} · {d.availability}</p>{d.claimant && <p className="text-sm mt-2">Receiver: {d.claimant.firstName} {d.claimant.lastName}</p>}{d.status === "APPROVED" && <p className="text-sm mt-2 flex gap-1"><MapPin className="w-4 h-4"/>{d.pickupLocation || "Pickup details available"}</p>}</div><div className="flex gap-2 items-center">{donor && d.status === "REQUESTED" && <><button onClick={() => act(d.id,"approve")} className="px-3 h-8 bg-[#4CAF50] text-white rounded text-xs flex gap-1 items-center"><Check className="w-3 h-3"/>Approve</button><button onClick={() => act(d.id,"decline")} className="px-3 h-8 border rounded text-xs flex gap-1 items-center"><X className="w-3 h-3"/>Decline</button></>}{donor && d.status === "APPROVED" && <button onClick={() => act(d.id,"complete")} className="px-3 h-8 bg-[#4CAF50] text-white rounded text-xs">Mark collected</button>}{!donor && d.status === "REQUESTED" && <button onClick={() => act(d.id,"cancel-request")} className="px-3 h-8 border rounded text-xs">Cancel request</button>}{donor && ["AVAILABLE","REQUESTED","APPROVED"].includes(d.status) && <button onClick={() => act(d.id,"cancel")} className="px-3 h-8 border rounded text-xs">Cancel listing</button>}</div></article>; })}{!donations.length && <div className="p-12 text-center border rounded-xl text-gray-500"><Clock className="mx-auto mb-2"/>No donation activity yet.</div>}</div></div>;
}
